# Generated by Django 6.0 on 2025-12-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_homework_checked_file_homework_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='gdrive_link',
            field=models.URLField(blank=True, help_text='Google Drive link for the assignment', null=True),
        ),
    ]
