# Generated by Django 6.0 on 2025-12-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_assignment_gdrive_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='subject',
            field=models.CharField(default='General', max_length=100),
        ),
    ]
