# Generated by Django 6.0 on 2025-12-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_assignment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='checked_gdrive_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
