# Generated by Django 6.0 on 2025-12-06 14:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_homework_checked_gdrive_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('chapter_name', models.CharField(max_length=200)),
                ('student_drive_link', models.URLField(help_text='Google Drive link for the chapter PDF/Folder')),
                ('teacher_notes_link', models.URLField(blank=True, help_text='Google Drive link for the checked notes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapter_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
